#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0 &
#polybar main -c .config/polybar/config.ini &

#if [[ $(xrandr -q | grep -w 'DP-1 connected') ]]; then
#		polybar external -c .config/polybar/config.ini &
#fi
. "${HOME}/.config/bspwm/scripts/startup"

bspc config border_width         0
bspc config window_gap           0

# Bordes
bspc config active_border_color '#0C1115'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color "ffffff"
bspc config border_width 3

# Comportamiento
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Aplicaciones
bspc rule -a Spotify desktop='^2' follow=on focus=on
bspc rule -a discord  desktop='^2' follow=on focus=on
bspc rule -a Rainbow\ Board desktop='^5'
bspc rule -a Anki desktop='^5'
bspc rule -a Emacs desktop='^3'
