#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0 &
#polybar main -c .config/polybar/config.ini &

#if [[ $(xrandr -q | grep -w 'DP-1 connected') ]]; then
#		polybar external -c .config/polybar/config.ini &
#fi
. "${HOME}/.config/bspwm/scripts/startup"

bspc config border_width         0
bspc config window_gap           0

bspc config focused_border_color "ffffff"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
